### ISSUE TITLE
expose cluster services

### ISSUE THREAD

**Issue by rigazilla** [jboss-dockerfiles/infinispan-server-operator#19]
Currently nothing is exposed outside openshift. Operator must expose services (hotrod and rest). Configuration should be provided via CR file.

**Comment by galderz** [comment]
Indeed. To be more precise, we need two services: one for hotrod and rest, and the other to enable DNS ping to work. For details, see how product defines services [here](https://github.com/jboss-container-images/jboss-datagrid-7-openshift-image/blob/datagrid73-dev/services/cache-service-template.yaml#L29-L63).
